#!/bin/bash

build=$1
location=$2
url_path=http://c758482.r82.cf2.rackcdn.com/
file_pattern="Sublime Text 2 Build "
hardware=`uname -m`
os=`uname -s`

if [ "${build}" = "" ]
then
  echo "usage: $0 <build> [location]"
  exit
fi

export file_get=$file_pattern$build

if [ "${location}" = "" ]
then
  location=`pwd`
fi

if [ "${hardware}" == "x86_64" ]
then
  if [ "${os}" == "Darwin" ]
  then
    export file_get=$file_get
  else
    export file_get="$file_get x64" 
  fi
else
  export file_get=$file_get
fi

if [ "${os}" == "Linux" ]
then
  export ext=.tar.bz2
elif [ "${os}" == "Darwin" ]
then
  export ext=.dmg
fi
export file_get=$file_get$ext

pushd $location

wget "$url_path$file_get"

if [ "${os}" == "Linux" ]
then
  tar jxvf "$file_get"
  mv "Sublime Text 2" sublime2-$build
  ln -s sublime2-$build sublime2
  rm *.bz2
else
  hdiutil mount "$file_get"
  mkdir -p sublime2-$build
  cp -R "/Volumes/Sublime Text 2/Sublime Text 2.app" "sublime2-$build/Sublime Text 2.app"
  ln -s sublime2-$build sublime2
  hdiutil unmount "/Volumes/Sublime Text 2"  
  rm *.dmg
fi

popd
